/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentoSlugRouteImport } from './routes/orcamento.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPagamentosDiariasRouteImport } from './routes/_authenticated/pagamentos-diarias'
import { Route as AuthenticatedPacotesRouteImport } from './routes/_authenticated/pacotes'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedFuncionariosRouteImport } from './routes/_authenticated/funcionarios'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDiagnosticoRouteImport } from './routes/_authenticated/diagnostico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos/index'
import { Route as AuthenticatedFeedbacksIndexRouteImport } from './routes/_authenticated/feedbacks/index'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos/index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes/index'
import { Route as AuthenticatedOrcamentosNovoRouteImport } from './routes/_authenticated/orcamentos/novo'
import { Route as AuthenticatedOrcamentosIdRouteImport } from './routes/_authenticated/orcamentos/$id'
import { Route as AuthenticatedEventosCreateRouteImport } from './routes/_authenticated/eventos/create'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes/novo'
import { Route as AuthenticatedClientesImportarRouteImport } from './routes/_authenticated/clientes/importar'
import { Route as AuthenticatedClientesIdEditarRouteImport } from './routes/_authenticated/clientes/$id.editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoSlugRoute = OrcamentoSlugRouteImport.update({
  id: '/orcamento/$slug',
  path: '/orcamento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosDiariasRoute =
  AuthenticatedPagamentosDiariasRouteImport.update({
    id: '/pagamentos-diarias',
    path: '/pagamentos-diarias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPacotesRoute = AuthenticatedPacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFuncionariosRoute =
  AuthenticatedFuncionariosRouteImport.update({
    id: '/funcionarios',
    path: '/funcionarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticoRoute =
  AuthenticatedDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedbacksIndexRoute =
  AuthenticatedFeedbacksIndexRouteImport.update({
    id: '/feedbacks/',
    path: '/feedbacks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosNovoRoute =
  AuthenticatedOrcamentosNovoRouteImport.update({
    id: '/orcamentos/novo',
    path: '/orcamentos/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIdRoute =
  AuthenticatedOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosCreateRoute =
  AuthenticatedEventosCreateRouteImport.update({
    id: '/eventos/create',
    path: '/eventos/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/clientes/novo',
    path: '/clientes/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesImportarRoute =
  AuthenticatedClientesImportarRouteImport.update({
    id: '/clientes/importar',
    path: '/clientes/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdEditarRoute =
  AuthenticatedClientesIdEditarRouteImport.update({
    id: '/clientes/$id/editar',
    path: '/clientes/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/pagamentos-diarias': typeof AuthenticatedPagamentosDiariasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orcamento/$slug': typeof OrcamentoSlugRoute
  '/clientes/importar': typeof AuthenticatedClientesImportarRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/eventos/create': typeof AuthenticatedEventosCreateRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/feedbacks/': typeof AuthenticatedFeedbacksIndexRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/pacotes': typeof AuthenticatedPacotesRoute
  '/pagamentos-diarias': typeof AuthenticatedPagamentosDiariasRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orcamento/$slug': typeof OrcamentoSlugRoute
  '/clientes/importar': typeof AuthenticatedClientesImportarRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/eventos/create': typeof AuthenticatedEventosCreateRoute
  '/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/feedbacks': typeof AuthenticatedFeedbacksIndexRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnostico': typeof AuthenticatedDiagnosticoRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/funcionarios': typeof AuthenticatedFuncionariosRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/pacotes': typeof AuthenticatedPacotesRoute
  '/_authenticated/pagamentos-diarias': typeof AuthenticatedPagamentosDiariasRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/orcamento/$slug': typeof OrcamentoSlugRoute
  '/_authenticated/clientes/importar': typeof AuthenticatedClientesImportarRoute
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/eventos/create': typeof AuthenticatedEventosCreateRoute
  '/_authenticated/orcamentos/$id': typeof AuthenticatedOrcamentosIdRoute
  '/_authenticated/orcamentos/novo': typeof AuthenticatedOrcamentosNovoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/_authenticated/feedbacks/': typeof AuthenticatedFeedbacksIndexRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/clientes/$id/editar': typeof AuthenticatedClientesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/diagnostico'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/funcionarios'
    | '/leads'
    | '/pacotes'
    | '/pagamentos-diarias'
    | '/relatorios'
    | '/auth/callback'
    | '/orcamento/$slug'
    | '/clientes/importar'
    | '/clientes/novo'
    | '/eventos/create'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes/'
    | '/eventos/'
    | '/feedbacks/'
    | '/orcamentos/'
    | '/clientes/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/agenda'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/diagnostico'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/funcionarios'
    | '/leads'
    | '/pacotes'
    | '/pagamentos-diarias'
    | '/relatorios'
    | '/auth/callback'
    | '/orcamento/$slug'
    | '/clientes/importar'
    | '/clientes/novo'
    | '/eventos/create'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/clientes'
    | '/eventos'
    | '/feedbacks'
    | '/orcamentos'
    | '/clientes/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnostico'
    | '/_authenticated/equipe'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/funcionarios'
    | '/_authenticated/leads'
    | '/_authenticated/pacotes'
    | '/_authenticated/pagamentos-diarias'
    | '/_authenticated/relatorios'
    | '/auth/callback'
    | '/orcamento/$slug'
    | '/_authenticated/clientes/importar'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/eventos/create'
    | '/_authenticated/orcamentos/$id'
    | '/_authenticated/orcamentos/novo'
    | '/_authenticated/clientes/'
    | '/_authenticated/eventos/'
    | '/_authenticated/feedbacks/'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/clientes/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OrcamentoSlugRoute: typeof OrcamentoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$slug': {
      id: '/orcamento/$slug'
      path: '/orcamento/$slug'
      fullPath: '/orcamento/$slug'
      preLoaderRoute: typeof OrcamentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos-diarias': {
      id: '/_authenticated/pagamentos-diarias'
      path: '/pagamentos-diarias'
      fullPath: '/pagamentos-diarias'
      preLoaderRoute: typeof AuthenticatedPagamentosDiariasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacotes': {
      id: '/_authenticated/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof AuthenticatedPacotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funcionarios': {
      id: '/_authenticated/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof AuthenticatedFuncionariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnostico': {
      id: '/_authenticated/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof AuthenticatedDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feedbacks/': {
      id: '/_authenticated/feedbacks/'
      path: '/feedbacks'
      fullPath: '/feedbacks/'
      preLoaderRoute: typeof AuthenticatedFeedbacksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/novo': {
      id: '/_authenticated/orcamentos/novo'
      path: '/orcamentos/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof AuthenticatedOrcamentosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$id': {
      id: '/_authenticated/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/create': {
      id: '/_authenticated/eventos/create'
      path: '/eventos/create'
      fullPath: '/eventos/create'
      preLoaderRoute: typeof AuthenticatedEventosCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/clientes/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/importar': {
      id: '/_authenticated/clientes/importar'
      path: '/clientes/importar'
      fullPath: '/clientes/importar'
      preLoaderRoute: typeof AuthenticatedClientesImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id/editar': {
      id: '/_authenticated/clientes/$id/editar'
      path: '/clientes/$id/editar'
      fullPath: '/clientes/$id/editar'
      preLoaderRoute: typeof AuthenticatedClientesIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticoRoute: typeof AuthenticatedDiagnosticoRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFuncionariosRoute: typeof AuthenticatedFuncionariosRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedPacotesRoute: typeof AuthenticatedPacotesRoute
  AuthenticatedPagamentosDiariasRoute: typeof AuthenticatedPagamentosDiariasRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedClientesImportarRoute: typeof AuthenticatedClientesImportarRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedEventosCreateRoute: typeof AuthenticatedEventosCreateRoute
  AuthenticatedOrcamentosIdRoute: typeof AuthenticatedOrcamentosIdRoute
  AuthenticatedOrcamentosNovoRoute: typeof AuthenticatedOrcamentosNovoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
  AuthenticatedFeedbacksIndexRoute: typeof AuthenticatedFeedbacksIndexRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedClientesIdEditarRoute: typeof AuthenticatedClientesIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticoRoute: AuthenticatedDiagnosticoRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFuncionariosRoute: AuthenticatedFuncionariosRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedPacotesRoute: AuthenticatedPacotesRoute,
  AuthenticatedPagamentosDiariasRoute: AuthenticatedPagamentosDiariasRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedClientesImportarRoute: AuthenticatedClientesImportarRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedEventosCreateRoute: AuthenticatedEventosCreateRoute,
  AuthenticatedOrcamentosIdRoute: AuthenticatedOrcamentosIdRoute,
  AuthenticatedOrcamentosNovoRoute: AuthenticatedOrcamentosNovoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
  AuthenticatedFeedbacksIndexRoute: AuthenticatedFeedbacksIndexRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedClientesIdEditarRoute: AuthenticatedClientesIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OrcamentoSlugRoute: OrcamentoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
